### ISSUE TITLE
Data Mapping

### ISSUE THREAD

**Issue by TunaOzk** [KefenGroup/turistomer-server#17]
## Görev Açıklaması
Kullanıcıdan alınan isterler, NER modeli tarafından işlendikten sonra etiketli verilerin incelenip, otel ve restoran verilerinde yer alan genel etiketlerle eşleştirilecektir.
## Görev Gereksinimleri ve Yapılacaklar
Görev açıklamasında bahsi geçen etiket eşleştirme problemin çözmek için one-to-many bir mapping uygulanmalıdır. Olayı açıklamak adına aşağıda bir örnek verilmiştir:

- Kullanıcı isteri: Balık yiyebileceğim restoran öner.
- NER model çıktısı: [ dish: fish ]
- Mapping: [ Seafood: fish, octopus... ]
- Seafood kategorisine ait bütün restoranlar getirilir

 ### Yapılacaklar
- [x] Etiket Eşleştirme
- [x] Semantic Similarity

## Yazılım Tasarımı
Bu görev için <a href="https://en.wikipedia.org/wiki/Semantic_similarity">Semantic Similarity </a> konusunun araştırılması yapılacak ve bunu gerçekleştirebilen NLP modelleri ya da matematiksel formüller bulunarak uygulanması planlanmaktadır. Aşağıda yapılması planlanan mapping mimarisi bulunmaktadır:
![image](https://github.com/KefenGroup/turistomer-server/assets/100032722/d41197e3-d67a-47ea-85cb-0901e2bef161)

## Görev Çıktısı
Görevin tamamlanması ile birlikte kullanıcıya isterleri doğrutulsunda restoran ve otel önermeleri gerçekleştirilecektir.

**Comment by OguzKaanOselmis** [comment]
Semantic eşleştirme Spacy kullanılarak similarity hesabı ile cuisine, amenity, purpose, fiyat bilgisi ve location bilgileri için implement edildi
