### ISSUE TITLE
Map Filter

### ISSUE THREAD

**Issue by keremyvnc** [KefenGroup/turistomer-server#19]
## Görev Açıklaması
Kullanıcının isteği üzerine harita üzerinden otel ve restorantların filtrelenmesi

## Görev Gereksinimleri ve Yapılacaklar
Harita üzerinden LLM den gelen veriye göre kullanıcıya belirli bir alan içerisinde istediği tür içeriğin(otel, restoran, kültürel yapı)
lokasyonu gösterilecek. Olayı şu olay örgüsüyle açıklayabiliriz.
- [ ] Kullanıcı prompt olarak Bana yakınımdaki balık restoranları göster
- [ ] Restoranlardan deniz mahsulü içeriği olan restoranlar filtrelenir.
- [ ] Restoranlardan kullanıcın konumuna yaklaşık 5 km uzaklığındaki restoranlar filtrelenir.
- [ ] Kullanıcının istediği özelliklere sahip restoranlar haritada gösterilir.

## Yazılım Tasarımı
- [ ] Load Data With External Geojson
- [ ] Layer Design on Map

## Görev Çıktısı
Görevin tamamlanması ile birlikte kullanıcıya isterleri doğrultusunda restoran ve otel önermeleri harita üzerinden gösterilecektir.

**Comment by OguzKaanOselmis** [comment]
Not going to be in production
