### ISSUE TITLE
Mapbox Category Search

### ISSUE THREAD

**Issue by keremyvnc** [KefenGroup/turistomer-server#29]
## Görev Açıklaması
Kullanıcılar tatilleri boyunca otel ve restoran bilgileri dışında farklı gereksinimleri olabilir. Bunlar eczane, park, benzin istasyonu gibi yerlerin bilgileri olabilir. Kullanıcıya haritada bu bilgilerin sağlanması gerekmektedir.
## Görev Gereksinimleri ve Yapılacaklar
Mapbox Search API kullanılarak kullanıcının konumuna yakınlığa bağlı olarak istediği kategorideki mekanların gösterilmesi.
 ### Yapılacaklar

- [ ] Mapbox Search API nasıl kullanılır öğrenilecek
- [ ] Mapbox Search API da category search yapılacak
- [ ] Kullanılacak kategoriler belirlenecek
- [ ] Alınan veriler kullanıcıya haritada gösterilecek

## Yazılım Tasarımı
Kullanılacak kategoriler belirlendikten sonra API aracığılıyla bu veriler alınacak. Haritanın sağ tarafında bu kategoriler için butonlar eklenicek. Kullanıcı butona bastığı zaman haritaya ilgili markerlar atanacak.

## Görev Çıktısı
Kullanıcı etrafındaki Point of Interest yerlerini görebilecek.

**Comment by OguzKaanOselmis** [comment]
Not going to be in production
