### ISSUE TITLE
Yapılacak Aktivite ve Etkinlik Verilerinin Toplanması

### ISSUE THREAD

**Issue by TunaOzk** [KefenGroup/turistomer-server#30]
## Görev Açıklaması
Görevin gerekli açıklamasına turistomer-client tarafında değinilmiştir. (turistomer-client-14#)
## Görev Gereksinimleri ve Yapılacaklar
Aktivite ve etkinlik verilerinin alınacaği sitenin incelenmesi ve uygun verilerin nerelerde olduğunun hangi html elementi içerisinde nasıl saklandığı araştırılmalıdır. Aktivite ve etkinlik verilerinin çekilmesi adına <a href="https://www.selenium.dev/">Selenium</a> ve <a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">Beautiful Soup</a>  araçlarının kullanılması gerekmektedir.
 ### Yapılacaklar
- [ ] Selenium ve BeautifulSoup kullanılarak veri elde edilmesi
- [ ] Aktivite ve etkinlik verilerinin incelenmesi ve araştırılması
## Yazılım Tasarımı
İlgili verilerin çekilmesi adına <a href="https://www.selenium.dev/">Selenium</a> ve <a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">Beautiful Soup</a> kullanarak #13'te olduğu gibi birtakım python scriptleri yazılması planlanmaktadır.

## Görev Çıktısı
Issue sonucunda kullanıcılar, seyahatleri sırasında bulundukları şehirlerdeki popüler aktivite etkinliklerden haberdar olabilecekler. Bu durumda kullanıcıların seyahat deneyimlerini olumlu anlamda etkileyecektir.

**Comment by OguzKaanOselmis** [comment]
Will not be in production
